---
version: "3.5"
services:
  network_importer:
    container_name: "network_importer"
    build:
      context: "."
      dockerfile: "Dockerfile"
      args:
        PYTHON_VER: "3.7.7"
    command: python local/main.py

    stdin_open: true
    tty: true
    env_file:
      - ".env"
    depends_on:
      - "batfish"
    volumes:
      - "./network_importer:/source/network_importer"
      - "./examples:/source/examples"
      - "./tests:/source/tests"
      - "./synclogs:/local/synclogs"
  batfish:
    container_name: "batfish-test"
    image: "batfish/batfish:2020.10.08.667"
    ports:
      - "9997:9997"
      - "9996:9996"
networks:
  default:
    name: nautobot-docker-compose_default
    external: true

volumes:
  synclogs: